---
title: "Assessing the Effectiveness of the Dutch Brain Research Registry for Participant Recruitment in Brain Research Studies: An Analysis of Sample Representativeness and Enrollment Rates"
author: 
  - Ganjiyev, Javid [^1]
bibliography: ../bibliography/biblio.bib
csl: ../csl/apa.csl
header-includes:
  - \usepackage{polyglossia}
  - \setmainlanguage{english}
  - \usepackage{booktabs}
  - \usepackage{caption} 
  - \captionsetup[table]{skip=10pt}
output:
  bookdown::pdf_document2:
    fig_caption: yes
    fig_height: 3
    fig_width: 4
    keep_tex: no
    latex_engine: xelatex
    number_sections: yes
    toc: no
geometry: margin=1in
link-citations: yes
urlcolor: blue
fontsize: 12pt
biblio-style: apalike
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, echo = TRUE, message = FALSE, warning = FALSE)
```

<!-- ======================================================================= -->
<!-- ============================== FOOTNOTES ============================== -->
<!-- ======================================================================= -->
[^1]: 20080146, [Github Repo](https://github.com/javidganjiyev/Midterm.git)

**Research question:**

How effective is the Dutch Brain Research Registry (DBRR) for study participant recruitment in terms of sample representativeness and enrollment rates?


**Hypothesis:**

DBRR is an effective tool for participant recruitment in brain research studies, resulting in a representative sample and high enrollment rates. The paper predicts that the DBRR will yield a sample that is fairly representative of the population at large with respect to age, sex, and education. Additionally, we expect to observe high enrollment rates in studies utilizing the DBRR as a recruitment tool, compared to studies using traditional recruitment methods.


**Thesis statement:**

DBRR is a valuable tool for participant recruitment in brain research studies, as demonstrated by its ability to generate a representative sample and high enrollment rates, as evidenced by its first results.


# Introduction

Neurodegenerative illnesses like Alzheimer's and Parkinson's require extensive study of the brain to uncover their origins and processes. Millions of people are afflicted by these diseases, which places a heavy strain on healthcare resources and the global economy. Researchers need to enroll a broad and representative sample of people with these conditions in order to create effective therapies and prevention measures. Yet, it might be difficult to recruit participants since it takes a lot of time, energy, and money.

DBRR is a platform developed to facilitate participant recruitment for brain research studies in the Netherlands. The DBRR allows individuals to register as potential study participants, creating a database of individuals interested in participating in brain research studies. The platform also provides researchers with a tool to search for potential participants based on specific inclusion and exclusion criteria.

The goal of this study is to assess the DBRR's performance in terms of participant recruitment. Specifically, this study aims to assess the representativeness of the sample generated by the DBRR and enrollment rates for brain research studies. To achieve these objectives, the study analyzes the design of the DBRR and its first results, as reported in a recent publication by @Zwanetal:2021.

Overall, this study contributes to the ongoing efforts to improve participant recruitment in brain research studies, ultimately advancing our understanding and treatment of neurodegenerative diseases.


## Literature Review

Participant recruitment is a major problem in Alzheimer's disease (AD) and associated dementia clinical studies. To address this issue, several studies have explored different recruitment strategies. @field:2019 conducted a study to recruit people with dementia using social media, radio, and newspapers. They found that the use of social media was the most effective strategy, leading to a higher number of participants.
Another study by [@grill2018constructing] aimed to construct a local potential participant registry for AD clinical research recruitment. The authors found that a registry that is tailored to the local population can improve the recruitment of participants in clinical trials.

@langbaum2020alzheimer developed an internet-based participant recruitment registry called the Alzheimer's Prevention Registry. The registry aims to expedite referrals to Alzheimer's studies. The authors found that the registry was effective in increasing the number of participants in AD prevention studies.

@vidoni:2018 emphasized the need for novel recruitment models to drive the success of AD trials. The authors suggested using community-based approaches, such as partnering with community organizations, to increase recruitment.

The Brain Health Registry was developed by [@weiner:2018] as a central online hub for neuroscience research recruitment, assessment, and follow-up. The registry proved to be an effective tool for recruiting and retaining participants in studies.

Lastly, @Zwanetal:2021 developed DBRR for participant recruitment in brain research studies. According to the authors, the DBRR successfully generated an educationally, racially, and sexually diverse sample of the general population. They also observed high enrollment rates in studies utilizing the DBRR as a recruitment tool, compared to studies using traditional recruitment methods.

Overall, the literature suggests that tailored recruitment strategies that utilize technology, community partnerships, and local registries can be effective in improving participant recruitment in AD clinical trials. The DBRR is a promising new tool for participant recruitment in the Netherlands.



\newpage
# References {#references}
<div id="refs"></div>

